### ISSUE TITLE
百度图片识别错误

### ISSUE THREAD

**Issue by regancz** [startzm/captcha_cnn#1]
我用4w+的样本训练之后，字符和图形的准确率都接近1了，但是我从百度图片找一张特别清晰的图片就无法识别了，没有噪声，交叉，变形，背景也是黑白的数字也无法识别，我不知道原理上到底是为啥不行呢，我改过文件格式，像素，但都没用。不是很懂为什么captcha生成的数据可以识别，而其他的识别不了

**Comment by startzm** [comment]
您好，您是使用captcha生成的数据集训练好以后识别百度找的图片出现识别错误吗？如果是的话是这样，每种图像都有自己的特征，一般来说，想要识别哪一类的验证码，就需要专门拿这类验证码的真实数据集去训练，比如我需要识别微博登录的验证码，那我训练的时候也就需要使用标注好的微博验证码的数据集，用captcha生成的验证码训练之后去识别微博的一定没法得到满意的效果，除非图像的各方面特征非常接近。如果想训练一套通用的验证码识别，一个模型搞定所有类型，是比较困难的，那需要大量的不同种类的数据集。

**Comment by regancz** [comment]
> 您好，您是使用captcha生成的数据集训练好以后识别百度找的图片出现识别错误吗？如果是的话是这样，每种图像都有自己的特征，一般来说，想要识别哪一类的验证码，就需要专门拿这类验证码的真实数据集去训练，比如我需要识别微博登录的验证码，那我训练的时候也就需要使用标注好的微博验证码的数据集，用captcha生成的验证码训练之后去识别微博的一定没法得到满意的效果，除非图像的各方面特征非常接近。如果想训练一套通用的验证码识别，一个模型搞定所有类型，是比较困难的，那需要大量的不同种类的数据集。

**Comment by regancz** [comment]
好的谢谢大佬，我也是刚学
